version: '3'
services:
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data

  postgres:
    image: postgis/postgis:14-3.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - "5433:5433"
    volumes:
      - postgres_superset:/var/lib/postgresql/data

  superset:
    image: baldosa/superset-ar
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py

volumes:
  redis:
  postgres_superset: