version: '3'
services:
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data

  postgres:
    image: postgis/postgis:14-3.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_superset:/var/lib/postgresql/data
    env_file:
      - .env

  superset:
    image: baldosa/superset:test
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ./mapa_view:/app/pythonpath/mapa_view
      - ./tools_view:/app/pythonpath/tools_view
      - ./dashboards.json:/tmp/dashboards.json
    env_file:
      - .env
volumes:
  redis:
  postgres_superset:
